version: 2
updates:
  # Go modules - Security updates only
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "sukhera"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "go"
    # Only create PRs for security updates
    allow:
      - dependency-type: "direct"

  # Frontend dependencies - Security updates only
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "sukhera"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "frontend"
    # Only create PRs for security updates
    allow:
      - dependency-type: "direct"

  # GitHub Actions - Security updates only
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "sukhera"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "ci"
    # Only create PRs for security updates
    allow:
      - dependency-type: "direct"

  # Docker dependencies - Security updates only
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "sukhera"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "docker"
    # Only create PRs for security updates
    allow:
      - dependency-type: "direct"